### ISSUE TITLE
is here a typo?

### ISSUE THREAD

**Issue by lexuszhi1990** [hodgka/Pixel-Recursive-Super-Resolution#1]

**Comment by hodgka** [comment]
There are a couple of typos I fixed locally but never got around to pushing. The main errors are that in trainers.py, `iters` should be `iterations` and `summary_op` should be `summarize`. Also images weren't working with tensorboard for me and I had to do other stuff, so I just commented out the `summary_writer.add_summary(summary_str, epochs)` in trainer.py, and `tf.summary.image(image_path, merged_image)` and uncommented `imsave(image_path, merged_image)`

My GPU died, but once I get a new one, I'll make sure all the code works and push it
